### ISSUE TITLE
[Bug] boogie exited while compiling Option::is_some<vector<T>>( )

### ISSUE THREAD

**Issue by guangyuz** [diem/diem#8645]
# 🐛 Bug

Boogie exited when compile 'Option::is_some<vector<T>>( )'. Below test can reproduce the error. It works fine in diem release v1.2, but fails in the latest build.

## To reproduce
 
**Code snippet to reproduce**
```rust
// Collection.move
address 0x1 {

module Collection {
    use 0x1::Option::{Self, Option};

    spec module {
        pragma verify = true;
        pragma aborts_if_is_strict = true;
    }
    
    struct Collection<T> has key {
        items: Option<vector<T>>,
    }

    fun destroy_empty<T>(c: Collection<T>){
        let Collection{ items } = c;
        Option::destroy_none(items);
    }

    spec destroy_empty {
        aborts_if Option::is_some<vector<T>>(c.items);
    }

}
}
```

**Stack trace/error message**
```
Error: Unexpected prover output (expected none): Move prover returns: [internal] boogie exited with compilation errors:
/var/folders/y0/b4m6m91d4cvdrdzzwb2y9pzc0000gn/T/.tmpNEtl3i/Collection.bpl(1758,52): Error: invalid type for argument 0 in application of $1_Option_$is_some'vec'vec'#0''': $1_Option_Option'vec'#0'' (expected: $1_Option_Option'vec'vec'#0''')
```
