### PR TITLE
[move-cli] Include stdlib in `move compile` by default

### LINKED ISSUE #8673: [cli] discrepancy between `compile` and `publish` commands
If you place the following code in `src/modules/Example.move`

```
module 0x1::Example {
  use 0x1::Signer;

  public fun f(account: &signer): address {
    Signer::address_of(account)
  }
}
```

, `move compile` and `move compile --mode stdlib` both fail with

```
error:

   ┌── src/modules/Example.move:2:7 ───
   │
 2 │   use 0x1::Signer;
   │       ^^^^^^^^^^^ Invalid 'use'. Unbound module: '0x1::Signer'
   │

error:

   ┌── src/modules/Example.move:5:5 ───
   │
 5 │     Signer::address_of(account)
   │     ^^^^^^ Unbound module alias 'Signer'
   │

```

However, `move sandbox publish` works just fine. I believe this is the correct behavior; `compile` seems to be failing to import stdlib dependencies. I suspect that this was introduced by 4e7f1a3cbfffaabb3cf76bfbe97265a57d61881a, but did not confirm this.

### PR DESCRIPTION
**Pull request by tzakian**
This includes the Move stdlib as dependencies in the `move compile` command, and also updates things so this command respects the modes that are passed as well. This fixes #8673 

## Tests

Added a test from #8673  to make sure that compilation will fail with `--mode bare` and will compile with the default mode setting (stdlib).

### CODE REVIEW

File: language/tools/move-cli/src/main.rs [hunk 1]
```diff
@@ -198,18 +198,27 @@ pub enum ExperimentalCommand {
...
     let move_args = Move::from_args();
+    let mode = Mode::new(move_args.mode);
 
     match &move_args.cmd {
         Command::Compile {
             source_files,
             no_source_maps,
             check,
         } => {
+            let stdlib_mode_interface_dir = mode
```
Comment (sblackshear) [inline language/tools/move-cli/src/main.rs:209]: Nit: `mode_interface_dir` might be slightly less confusing, since there is a `stdlib` mode, but `mode` could be (e.g.) `bare` or `diem`?

**Review by sblackshear — APPROVED** [review]
Thanks!

**Review by sblackshear — DISMISSED** [review]

**Review by sblackshear — DISMISSED** [review]
