### ISSUE TITLE
[cli] discrepancy between `compile` and `publish` commands

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#8673]
If you place the following code in `src/modules/Example.move`

```
module 0x1::Example {
  use 0x1::Signer;

  public fun f(account: &signer): address {
    Signer::address_of(account)
  }
}
```

, `move compile` and `move compile --mode stdlib` both fail with

```
error:

   ┌── src/modules/Example.move:2:7 ───
   │
 2 │   use 0x1::Signer;
   │       ^^^^^^^^^^^ Invalid 'use'. Unbound module: '0x1::Signer'
   │

error:

   ┌── src/modules/Example.move:5:5 ───
   │
 5 │     Signer::address_of(account)
   │     ^^^^^^ Unbound module alias 'Signer'
   │

```

However, `move sandbox publish` works just fine. I believe this is the correct behavior; `compile` seems to be failing to import stdlib dependencies. I suspect that this was introduced by 4e7f1a3cbfffaabb3cf76bfbe97265a57d61881a, but did not confirm this.

**Comment by tzakian** [comment]
That PR is the most likely cause -- I'll take a look at a fix for this :)
